return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = "BufReadPost",
	auto_install = true,
	cmd = {
		"TSInstall",
		"TSUpdate",
		"TSInstallInfo",
		"TSEnable",
		"TSDisable",
		"TSModuleInfo",
		"TSUninstall",
	},
	opts = {
		ensure_installed = {
			"lua",
			"vim",
			"c",
			"cpp",
			"csv",
			"comment",
			"javascript",
			"json",
			"typescript",
			"tsx",
			"markdown",
			"markdown_inline",
			"python",
			"ruby",
			"css",
			"html",
			"gitignore",
			"yaml",
			"typst",
			"latex",
		},
		highlight = { enable = true },
		indent = { enable = true },
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}
